### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by NobbZ** [filipegoncalves/rust-config#8]
The linked documentation from crates.io is not available any more.

**Comment by filipegoncalves** [comment]
Hi, thanks for reporting, this seems to be an issue with github. I contacted them and will hopefully have an update soon.

**Comment by filipegoncalves** [comment]
This is solved now.

**Comment by NobbZ** [comment]
I still can't access documentation using the link from README, neither does the link from crates.io work.

**Comment by filipegoncalves** [comment]
That's weird, can you show me what exactly happens?

Try these URLs:
- http://codinghighway.com/rust-config/config/
- http://filipegoncalves.github.io/rust-config/config/

It works seamlessly here.

**Comment by NobbZ** [comment]
The second redirects to the first and the first one does show me the following:

![rust-config-docs](https://cloud.githubusercontent.com/assets/58951/11162949/762c9202-8abb-11e5-979a-aaad979d143c.png)

**Comment by filipegoncalves** [comment]
This issue appears to be related to the source user network where the request comes from. E.g. I can open it from my home connection, but on my company's network it shows the same error.

I am forwarding this issue to Github again.

Thanks for reporting, I'll keep this issue updated.

**Comment by filipegoncalves** [comment]
It should be fixed now - can you check?
